# Generated by Django 5.1.7 on 2025-03-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(choices=[('napitki', 'Напитки'), ('eda', 'Еда'), ('stakany', 'Стаканы'), ('zerno_kofe', 'Зерна кофе')], max_length=20)),
            ],
        ),
    ]
